=== GTNDYanagisawa/merchandise/bin/ext-commerce/solrfacetsearch/resources/config/SolrFacetConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">

	<xs:complexType name="indexconfig">
		<xs:sequence>
			<xs:element name="exportpath" type="xs:string" minOccurs="0"
				maxOccurs="1" />
			<xs:element name="batchSize" type="xs:int" minOccurs="0"
				maxOccurs="1" default="100" />
			<xs:element name="numberOfThreads" type="xs:int" minOccurs="0"
				maxOccurs="1" default="1" />
			<xs:element nillable="false" name="indexMode" type="indexMode" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>


	<xs:complexType name="itemTypes">
		<xs:sequence>
			<xs:element name="itemType" type="itemType" minOccurs="0"
				maxOccurs="100" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="properties">
		<xs:sequence>
			<xs:element name="property" type="property" minOccurs="0"
				maxOccurs="100" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="itemType">
		<xs:sequence>
			<xs:element name="properties" type="properties" minOccurs="0"
				maxOccurs="1" />
			<xs:element name="flexibleSearchUpdateQueries" type="flexibleSearchUpdateQueries"
				minOccurs="1" maxOccurs="1" />
		</xs:sequence>

		<xs:attribute name="code" type="xs:string" use="required" />

		<xs:attribute name="variant" use="optional" default="false"
			type="xs:boolean" />

		<xs:attribute name="identityProvider" type="xs:string"
			use="optional" />

		<xs:attribute name="modelLoader" type="xs:string" use="optional" />
		
		<xs:attribute name="valuesProvider" type="xs:string" use="optional" />
		
		<xs:attribute name="indexName" type="xs:string" use="optional" />
		
		<xs:attribute name="solrResultConverter" type="xs:string" use="optional" />
		

	</xs:complexType>


	<xs:complexType name="fsQuery">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="injectLastIndexTime" type="xs:boolean"
					default="false" use="optional" />
				<xs:attribute name="injectCurrentDate" type="xs:boolean"
					default="false" use="optional" />
				<xs:attribute name="injectCurrentTime" type="xs:boolean"
					default="false" use="optional" />
				<xs:attribute name="parameterProvider" type="xs:string"
					use="optional" />
				<xs:attribute name="user" type="xs:string" use="optional"
					default="anonymous" />
			</xs:extension>
		</xs:simpleContent>

	</xs:complexType>

	<xs:complexType name="flexibleSearchUpdateQueries">
		<xs:sequence>
			<xs:element name="fullIndexQuery" type="fsQuery"
				minOccurs="1" maxOccurs="1" />
			<xs:element name="updateIndexQuery" type="fsQuery"
				minOccurs="1" maxOccurs="1" />
			<xs:element name="deleteFromIndexQuery" type="fsQuery"
				minOccurs="0" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>


	<xs:complexType name="property">
		<xs:sequence>
			<xs:element name="rangeSets" type="rangeSets" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required" />
		<xs:attribute name="type" use="required" type="propertyType" />
		<xs:attribute name="sortableType" use="optional" type="propertyType" />
		<xs:attribute name="valueProvider" type="xs:string" use="optional" />
		<xs:attribute name="facet" type="xs:boolean" use="optional"
			default="false" />
		<xs:attribute name="localized" type="xs:boolean" use="optional"
			default="false" />
		<xs:attribute name="currency" type="xs:boolean" use="optional"
			default="false" />
		<xs:attribute name="multiValue" type="xs:boolean" use="optional"
			default="false" />
		<xs:attribute name="rangeSet" type="xs:string" use="optional" />
		<xs:attribute name="facetDisplayNameProvider" type="xs:string" use="optional" />
		<xs:attribute name="exportId" type="xs:string" use="optional"/>
		<xs:attribute name="facetType" type="facetType" use="optional" />
	</xs:complexType>

	<xs:complexType name="endpointURL">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="master" type="xs:boolean" use="optional"
					default="false" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="endpointURLs">
		<xs:sequence>
			<xs:element name="endpointURL" type="endpointURL"
				minOccurs="1" maxOccurs="100" />
		</xs:sequence>
	</xs:complexType>

	<xs:simpleType name="mode">
		<xs:restriction base="xs:NMTOKEN">
			<xs:enumeration value="standalone" />
			<xs:enumeration value="embedded" />
			<xs:enumeration value="xml_export" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="propertyType">
		<xs:restriction base="xs:NMTOKEN">
			<xs:enumeration value="boolean" />
			<xs:enumeration value="int" />
			<xs:enumeration value="string" />
			<xs:enumeration value="sortabletext" />
			<xs:enumeration value="text" />
			<xs:enumeration value="float" />
			<xs:enumeration value="double" />
			<xs:enumeration value="date" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="indexMode">
		<xs:restriction base="xs:NMTOKEN">
			<xs:enumeration value="DIRECT" />
			<xs:enumeration value="TWO_PHASE" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="solrconfig">
		<xs:sequence>
			<xs:element name="mode" type="mode" maxOccurs="1"
				minOccurs="1" />
			<xs:element name="clusterconfig" type="clusterconfig"
				maxOccurs="1" minOccurs="0" />
		</xs:sequence>
	</xs:complexType>

	<xs:element name="config">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="solrconfig" type="solrconfig"
					minOccurs="1" maxOccurs="1" />
				<xs:element name="indexconfig" type="indexconfig"
					minOccurs="1" maxOccurs="1" />
				<xs:element name="itemTypes" type="itemTypes" minOccurs="1"
					maxOccurs="1" />
			</xs:sequence>

		</xs:complexType>
	</xs:element>

	<xs:complexType name="clusterconfig">
		<xs:sequence>
			<xs:element name="aliveCheckInterval" type="timeoutValue"
				minOccurs="0" maxOccurs="1" />
			<xs:element name="connectionTimeout" type="timeoutValue"
				minOccurs="0" maxOccurs="1" />
			<xs:element name="readTimeout" type="timeoutValue"
				minOccurs="0" maxOccurs="1" />
			<xs:element name="endpointURLs" type="endpointURLs"
				minOccurs="0" maxOccurs="1" />
		</xs:sequence>
		<xs:attribute name="embeddedMaster" type="xs:boolean"
			use="optional" default="false" />
	</xs:complexType>

	<xs:simpleType name="timeoutValue">
		<xs:restriction base="xs:int">
			<xs:minInclusive value="0" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:complexType name="rangeSets">
		<xs:sequence>
			<xs:element name="rangeSet" type="rangeSet" minOccurs="1" maxOccurs="100"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="rangeSet">
		<xs:attribute name="name" type="xs:string"/>
	</xs:complexType>
	
	<xs:simpleType name="facetType">
		<xs:restriction base="xs:NMTOKEN">
			<xs:enumeration value="Refine" />
			<xs:enumeration value="MultiSelectAnd" />
			<xs:enumeration value="MultiSelectOr" />
		</xs:restriction>
	</xs:simpleType>
	
</xs:schema>

=== GTNDYanagisawa/merchandise/bin/ext-commerce/solrfacetsearch/resources/test/TestFacetConfigModelPropertyResolver.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../config/SolrFacetConfig.xsd">
  <solrconfig>
    <mode>standalone</mode>
    <clusterconfig>
    	<endpointURLs>
		    <endpointURL master="true">http://localhost:8983/solr</endpointURL>
        </endpointURLs>
    </clusterconfig>
  </solrconfig>
  <indexconfig>
    <exportpath>testexportpath</exportpath>
    <batchSize>100</batchSize>
  </indexconfig>
  <itemTypes>
    <itemType code="Product" variant="false" identityProvider="itemIdentityProvider">
      <properties>
        <property facet="true" name="name" type="text" rangeSet="stringRange" localized="true" facetType="MultiSelectOr"/>
        <property facet="false" name="code" type="text" rangeSet="stringRange" />
        <property facet="false" name="description" type="text" localized="true"/>
        <property facet="false" name="onlineDate" type="date" rangeSet="dateRange"/>
      </properties>
      <flexibleSearchUpdateQueries>
        <fullIndexQuery injectCurrentDate="false" injectCurrentTime="false" injectLastIndexTime="false" user="anonymous">fullIndexQuery</fullIndexQuery>
        <updateIndexQuery injectCurrentDate="false" injectCurrentTime="false" injectLastIndexTime="false" user="anonymous">updateIndexQuery</updateIndexQuery>
        <deleteFromIndexQuery injectCurrentDate="false" injectCurrentTime="true" injectLastIndexTime="false" user="anonymous">deleteFromIndexQuery</deleteFromIndexQuery>
      </flexibleSearchUpdateQueries>
    </itemType>
  </itemTypes>
</config>

=== GTNDYanagisawa/merchandise/bin/ext-commerce/solrfacetsearch/resources/test/TestParameterProviders.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../config/SolrFacetConfig.xsd">
  <solrconfig>
    <mode>embedded</mode>
    <clusterconfig embeddedMaster="true">
    	<aliveCheckInterval>5000</aliveCheckInterval>
    	<connectionTimeout>5000</connectionTimeout>
    	<readTimeout>5000</readTimeout>
    	<endpointURLs>
      		<endpointURL master="true">http://localhost:8983/solr</endpointURL>
    	</endpointURLs>
    </clusterconfig>
  </solrconfig>
  <indexconfig>
    <batchSize>100</batchSize>
  </indexconfig>
  <itemTypes>
    <itemType code="Product" variant="false" identityProvider="itemIdentityProvider">
      <properties>
      	<property name="code" type="string"/>
      	<property name="name" type="text" sortableType="sortabletext" localized="true"/>
      </properties>
      <flexibleSearchUpdateQueries>
        <fullIndexQuery user="anonymous" parameterProvider="mockContextAwareParameterProvider">
			SELECT {pk} FROM {Product}
        </fullIndexQuery>
        <updateIndexQuery user="anonymous" injectLastIndexTime="true">
			SELECT {PK} FROM {Product} 
			WHERE {modifiedtime} &gt;= ?lastIndexTime
        </updateIndexQuery>
        <deleteFromIndexQuery parameterProvider="simpleParameterProvider">
        	SELECT {PK} FROM {Product} WHERE catalogVersion = ?catalogVersion1
        </deleteFromIndexQuery>
      </flexibleSearchUpdateQueries>
    </itemType>
  </itemTypes>
</config>

=== GTNDYanagisawa/merchandise/bin/ext-commerce/solrfacetsearch/resources/config/SolrFacetConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="SolrFacetConfig.xsd">

  <solrconfig>
    <mode>embedded</mode>
    <clusterconfig>
    	<endpointURLs>
      		<endpointURL timeout="0">endpointURL</endpointURL>
		    <endpointURL timeout="0">endpointURL2</endpointURL>
    	</endpointURLs>
    </clusterconfig>
  </solrconfig>
  
  <indexconfig>
    <exportpath>exportpath</exportpath>
    <batchSize>100</batchSize>
    <numberOfThreads>1</numberOfThreads>
  </indexconfig>
  
  <itemTypes>
    <itemType code="" variant="false" identityProvider="">
      <properties>
        <property facet="true" name="" type="string" rangeSet="" valueProvider=""/>
      </properties>
      <flexibleSearchUpdateQueries>
        <fullIndexQuery user="anonymous" injectLastIndexTime="true" injectCurrentDate="false" parameterProvider="">
          SELECT {PK} FROM ....
        </fullIndexQuery>
        <updateIndexQuery user="anonymous">
          SELECT {PK} FROM ....
        </updateIndexQuery>
        <deleteFromIndexQuery user="anonymous">
          SELECT {PK} FROM ....
        </deleteFromIndexQuery>
      </flexibleSearchUpdateQueries>
    </itemType>
    </itemTypes>
  
</config>

=== GTNDYanagisawa/merchandise/bin/ext-commerce/solrfacetsearch/resources/test/IntegrationTestFacetConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../config/SolrFacetConfig.xsd">
  <solrconfig>
    <mode>embedded</mode>
    <clusterconfig embeddedMaster="true">
    	<aliveCheckInterval>5000</aliveCheckInterval>
    	<connectionTimeout>5000</connectionTimeout>
    	<readTimeout>5000</readTimeout>
    	<endpointURLs>
      		<endpointURL master="true">http://localhost:8983/solr</endpointURL>
    	</endpointURLs>
    </clusterconfig>
  </solrconfig>
  <indexconfig>
    <batchSize>100</batchSize>
  </indexconfig>
  <itemTypes>
    <itemType code="Product" variant="false" identityProvider="itemIdentityProvider">
      <properties>
      	<property name="code" type="string"/>
      	<property name="name" type="text" sortableType="sortabletext" localized="true"/>
      	<property name="description" type="text" localized="true"/>
        <property facet="true" name="manufacturerName" type="string" sortableType="sortabletext"/>
        <property facet="true" name="price" type="double" valueProvider="productPriceValueProvider" rangeSet="priceRanges" currency="true"/>
        <property facet="true" name="processor" type="string" valueProvider="classificationPropertyValueProvider" multiValue="true"/>
        <property facet="true" name="categoryName" type="string" valueProvider="categoryNameValueProvider" localized="true" multiValue="true"/> 
        <property facet="true" name="categoryCode" facetDisplayNameProvider="categoryFacetDisplayNameProvider" type="string" valueProvider="categoryCodeValueProvider" multiValue="true"/>
        <property facet="true" name="type" type="string" valueProvider="classificationPropertyValueProvider" localized="true" multiValue="true"/>
      </properties>
      <flexibleSearchUpdateQueries>
        <fullIndexQuery user="anonymous">
			SELECT {pk} FROM {Product}
        </fullIndexQuery>
        <updateIndexQuery user="anonymous" injectLastIndexTime="true">
			SELECT {PK} FROM {Product} 
			WHERE {modifiedtime} &gt;= ?lastIndexTime
        </updateIndexQuery>
        <deleteFromIndexQuery>
        	SELECT {PK} FROM {Product} WHERE code = 'HW2310-1001'
        </deleteFromIndexQuery>
      </flexibleSearchUpdateQueries>
    </itemType>
  </itemTypes>
</config>
